version: '3'

services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./:/usr/share/nginx/html
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/indexOnePage.html"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    restart: unless-stopped